[package]
name = "dijkstra-rs-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
dijkstra-rs = { path = "../dijkstra-rs" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "dijkstra"
harness = false